config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :users
  resources :categories
  resources :books

  root 'transactions#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
    @books = Book.order(sort_column + " " + sort_direction)
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:borrower_name, :borrower_book, :borrower_date, :borrower_date_return)
    end

    #sorting
    def sort_column
      Book.column_names.include?(params[:sort]) ? params[:sort] : "title"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_for(transaction) do |f| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Name" %>
    <%= f.text_field :borrower_name  %>
  </div>

  <div class="field">
    <%= f.label "Book" %>
    <%= f.collection_select :borrower_book, Book.all, :id, :title, include_blank: true %>
  </div>

  <div class="field">
    <%= f.label "From" %>
    <%= f.datetime_select :borrower_date %>
  </div>

  <div class="field">
    <%= f.label "Until" %>
    <%= f.datetime_select :borrower_date_return %>
  </div>

  <div class="actions">
    <%= f.submit "Borrow" %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th><%= sortable "title" %></th>
      <th>Author Name</th>
      <th>Released date</th>
      <th><%= sortable "category_id" %></th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author_name %></td>
        <td><%= book.released_date %></td>
        <td><%= book.category.name %></td>
        <td><%= book.status %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Borrow Some Book', new_transaction_path %>

app/views/transactions/new.html.erb
<h1>Borrow Some Book</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Borrower name:</strong>
  <%= @transaction.borrower_name %>
</p>

<p>
  <strong>Borrower book:</strong>
  <%= @transaction.borrower_book %>
</p>

<p>
  <strong>Borrower date:</strong>
  <%= @transaction.borrower_date %>
</p>

<p>
  <strong>Borrower date return:</strong>
  <%= @transaction.borrower_date_return %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>